/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package controleacademico.view.pagesAdmin;

import controleacademico.controller.DisciplinaController;
import controleacademico.controller.RendimentoEscolarController;
import controleacademico.controller.TurmaController;
import controleacademico.controller.UsuarioLogadoController;
import controleacademico.model.Aluno;
import controleacademico.model.Disciplina;
import controleacademico.model.RendimentoEscolar;
import controleacademico.model.TurmaModel;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Double
 */
public class MenuTurmaDisciplina extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuTurmaDisciplina
     */
    public MenuTurmaDisciplina() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        ExibirInformacoes();

        //JComboBox<Disciplina> cbDisciplina = new JComboBox<>(DisciplinaController.listaTodasDisciplina().toArray(new Disciplina[0]));
        // Carregar disciplinas
        DefaultComboBoxModel<String> modeloDisciplinas = new DefaultComboBoxModel<>();
        for (Disciplina d : DisciplinaController.listaTodasDisciplina()) {
            modeloDisciplinas.addElement(d.getNome());
            //cbxDisciplina.addItem(d.getNome());
        }
        cbxDisciplina.setModel(modeloDisciplinas);

    }

    private void ExibirInformacoes() {
        DefaultTableModel tbTurma = (DefaultTableModel) jtbTurmaDisciplina.getModel();
        ArrayList<TurmaModel> turmaData = TurmaController.listaTodasTurma();
        tbTurma.setRowCount(0);
        Disciplina disciplina = null;
        String nomeDisciplina = "";
        String nomeEmenta = "";
        String nomesProfessores = "";

        for (TurmaModel turma : turmaData) {
            //System.out.println("Tamanho do Array " + turma.getDisciplinas().isEmpty());

            if (turma.getDisciplinas() != null && !turma.getDisciplinas().isEmpty()) {
                for (Disciplina discipli : turma.getDisciplinas()) {
                    //System.out.println("Length " + turma.getDisciplinas().size());
                    if (discipli != null) {
                        disciplina = discipli;
                        nomeDisciplina = nomeDisciplina.concat(discipli.getNome() + ", ");
                    }

                }
            }

            tbTurma.addRow(new Object[]{
                turma.getId(),
                nomeDisciplina,
                nomeEmenta,
                nomesProfessores,});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxTurmas = new javax.swing.JComboBox<>();
        cbxDisciplina = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTurmaDisciplina = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        btnSave.setBackground(new java.awt.Color(0, 102, 94));
        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Savar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jtbTurmaDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Id Disciplina", "Disciplinas", "Ementa", "Professsores"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbTurmaDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbTurmaDisciplinaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbTurmaDisciplina);
        if (jtbTurmaDisciplina.getColumnModel().getColumnCount() > 0) {
            jtbTurmaDisciplina.getColumnModel().getColumn(0).setResizable(false);
            jtbTurmaDisciplina.getColumnModel().getColumn(2).setResizable(false);
            jtbTurmaDisciplina.getColumnModel().getColumn(3).setResizable(false);
            jtbTurmaDisciplina.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel2.setText("Disciplina");

        jLabel1.setText("Turmas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTurmas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (jtbTurmaDisciplina.getSelectedRow() != -1) {
            int idTurm = (int) jtbTurmaDisciplina.getValueAt(jtbTurmaDisciplina.getSelectedRow(), 0);
            //int idDisci= (int) jtbTurmaDisciplina.getValueAt(jtbTurmaDisciplina.getSelectedRow(), 1);

            //Pegar disciplina
            String disciplina = (String) cbxDisciplina.getSelectedItem();

            TurmaModel turmaById = TurmaController.getTurmaById(idTurm);
            Disciplina getDisciplinaByName = DisciplinaController.getDisciplinaByName(disciplina);
            System.out.println("Int id na view: " + turmaById.getId());
            if (getDisciplinaByName == null) {
                System.out.println("Disciplina  está vazia");
            }

            if (turmaById != null) {
                ArrayList<Disciplina> disciplinas1 = new ArrayList<>();
                disciplinas1.add(getDisciplinaByName);
                //turmaById.setDisciplinas(disciplinas1);
                System.out.println("Visualizar na própia view " + turmaById.getId());
                turmaById.addDisciplina(getDisciplinaByName);
                turmaById.setCapacidade(20);

                JOptionPane.showMessageDialog(null, "Disciplina Vinculada Com Sucesso!");
            }
            ExibirInformacoes();

        } else {
            JOptionPane.showMessageDialog(null, "Selecion uma turma");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jtbTurmaDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTurmaDisciplinaMouseClicked
        // TODO add your handling code here:
        if (jtbTurmaDisciplina.getSelectedRow() != -1) {
            int idTurm = (int) jtbTurmaDisciplina.getValueAt(jtbTurmaDisciplina.getSelectedRow(), 0);

        }
    }//GEN-LAST:event_jtbTurmaDisciplinaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbxDisciplina;
    private javax.swing.JComboBox<String> cbxTurmas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbTurmaDisciplina;
    // End of variables declaration//GEN-END:variables
}
