/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controleacademico.view;

import controleacademico.ControleAcademico;
import controleacademico.controller.AlunoController;
import controleacademico.controller.ProfessorController;
import controleacademico.model.Professor;
import controleacademico.model.Aluno;
import controleacademico.model.User;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Double
 */
public class CadastrarUtilizador extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarUtilizador
     */
    ProfessorController professor = new ProfessorController();
    AlunoController aluno = new AlunoController();

    public CadastrarUtilizador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbCargo = new javax.swing.JLabel();
        tfdCargo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jpfPassoword = new javax.swing.JPasswordField();
        jpfPasswordConfirm = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        cbxRole = new javax.swing.JComboBox<>();
        btnVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spDate = new javax.swing.JSpinner();
        tfdNomeUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastrar Utilizador");

        jLabel2.setText("Nome");

        jLabel3.setText("Tipo");

        lbCargo.setText("Cargo");

        jLabel5.setText("Senha");

        jpfPassoword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfPassowordActionPerformed(evt);
            }
        });

        jLabel6.setText("Confirmar Senha");

        btnSave.setText("Registar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cbxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professor", "Aluno" }));
        cbxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRoleActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel4.setText("Data de Nascimento");

        spDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(-1419511500000L), new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));

        tfdNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdNomeUsuarioActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome de Usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addGap(203, 203, 203)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbCargo)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tfdNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(spDate, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                        .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jpfPassoword, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(39, 39, 39)
                                .addComponent(jpfPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(223, 223, 223))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(545, 545, 545))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(spDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxRole, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCargo))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpfPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jpfPassoword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(57, 57, 57)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpfPassowordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfPassowordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpfPassowordActionPerformed

    private void cbxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRoleActionPerformed
        // TODO add your handling code here:
        String opcoaSelecionada = (String) cbxRole.getSelectedItem();
        if (opcoaSelecionada.equals("Aluno")) {
            tfdCargo.setVisible(false);
            lbCargo.setVisible(false);

        } else {
            tfdCargo.setVisible(true);
            lbCargo.setVisible(true);
        }
    }//GEN-LAST:event_cbxRoleActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String role = (String) cbxRole.getSelectedItem();
        Professor professorModel = new Professor();
        Aluno AlunoModel = new Aluno();

        //professorModel.setDataNascimento();
        Date dataNascimento1 = (Date) spDate.getValue();
        char[] password1 = jpfPassoword.getPassword();
        char[] password2 = jpfPasswordConfirm.getPassword();

        String userName = tfdNome.getText() + "" + professor.newId();
        String password = new String(password1);
        String passwordConform = new String(password2);
        User usersAc = ControleAcademico.searchUserName(tfdNomeUsuario.getText());

        professorModel.setNome(tfdNome.getText());
        professorModel.setDataNascimento(dataNascimento1);
        professorModel.setCargo(tfdCargo.getText());
        professorModel.setId(professor.newId());
        professorModel.setUserName(tfdNomeUsuario.getText());
        professorModel.setPassword(passwordConform);

        if (password.equals(passwordConform)) {

            //User usersAcade = ControleAcademico.searchUserName(professorModel.getUserName());
            if (usersAc == null) {
                if (role.equals("Professor")) {
                    boolean result = ControleAcademico.adicionarUsuario(professorModel);
                    if (result) {
                        JOptionPane.showMessageDialog(null, "Usuario Criado com sucesso!");
                        tfdCargo.setText("");
                        tfdNome.setText("");
                        tfdNomeUsuario.setText("");
                        jpfPassoword.setText("");
                        jpfPasswordConfirm.setText("");
                        spDate.setValue(new Date());

                    } else {
                        JOptionPane.showMessageDialog(null, "Usuario Não cadastrado!");
                    }
                } else {
                    //Registar Aluno
                    AlunoModel.setNome(tfdNome.getText());
                    AlunoModel.setId(professor.newId());
                    AlunoModel.setUserName(tfdNomeUsuario.getText());
                    AlunoModel.setPassword(passwordConform);
                    boolean result = ControleAcademico.adicionarUsuario(AlunoModel);
                    if (result) {
                        JOptionPane.showMessageDialog(null, "Usuario Criado com sucesso!");
                        tfdCargo.setText("");
                        tfdNome.setText("");
                        tfdNomeUsuario.setText("");
                        jpfPassoword.setText("");
                        jpfPasswordConfirm.setText("");
                        spDate.setValue(new Date());

                    } else {
                        JOptionPane.showMessageDialog(null, "Usuario Não cadastrado!");
                    }
                    
                }

            } else {
                JOptionPane.showMessageDialog(null, "Já temos esse usuário Cadastrado");
            }
        } else {
            System.out.println(" Password Diferentes " + password + " != " + passwordConform);
            JOptionPane.showMessageDialog(null, "Palavra Passe não coêncidem");
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void tfdNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdNomeUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUtilizador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarUtilizador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jpfPassoword;
    private javax.swing.JPasswordField jpfPasswordConfirm;
    private javax.swing.JLabel lbCargo;
    private javax.swing.JSpinner spDate;
    private javax.swing.JTextField tfdCargo;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JTextField tfdNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
