/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controleacademico.view;

import controleacademico.controller.UsuarioController;
import controleacademico.controller.TurmaController;
import controleacademico.controller.DisciplinaController;
import controleacademico.controller.RendimentoEscolarController;
import controleacademico.controller.UsuarioLogadoController;
import controleacademico.model.Aluno;
import controleacademico.model.Disciplina;
import controleacademico.model.TurmaModel;
import controleacademico.model.User;
import controleacademico.model.Professor;
import controleacademico.model.RendimentoEscolar;
import controleacademico.view.pageProfessor.MenuHome;
import controleacademico.view.pageProfessor.MenuMinhaTurma;
import controleacademico.view.pageProfessor.MenuMedia;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Double
 */
public class ProfessorPainel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPainelMain
     */
    Color DefaultColor, ClickedColor;

    public ProfessorPainel() {
        initComponents();
        DefaultColor = new Color(40, 40, 40);
        ClickedColor = new Color(13, 13, 13);

        menuHome.setBackground(ClickedColor);
        menuMinhaTurma.setBackground(DefaultColor);
        menuMedia.setBackground(DefaultColor);

        ExibirInformacoes();
        User usuarioLogado = UsuarioLogadoController.getUsuarioLogado();
        //System.out.println("User" + usuarioLogado.getNome());
        if (UsuarioLogadoController.isUsuarioLogado()) {
            lbUserLogged.setText("Hello, " + usuarioLogado.getNome());
            System.out.println("Usuario Logado");
        } else {
            System.out.println("Usuario Erro de novo" + UsuarioLogadoController.isUsuarioLogado());

        }
        //UsuarioLogadoController.getUsuarioLogado();
    }

    private void ExibirInformacoes() {
        //ArrayList<TurmaModel> TurmaData = TurmaController.listaTodasTurma();
        Professor usuarioLogado = (Professor) UsuarioLogadoController.getUsuarioLogado();
        ArrayList<TurmaModel> turmaData = TurmaController.getTurmaByProfessor(usuarioLogado);
        DefaultTableModel tbTurma = (DefaultTableModel) jtbTurma.getModel();

        tbTurma.setRowCount(0);
        Disciplina disciplina = null;
        for (TurmaModel turma : turmaData) {
            for (Disciplina disc : turma.getDisciplina()) {
                disciplina = disc;
                //System.err.println("Disciplinas do mesmo" + disc.getNome());
            }
            
            tbTurma.addRow(new Object[]{
                turma.getId(),
                disciplina.getNome(),
                disciplina.getEmenta()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        pnTerminarSessão = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        menuMinhaTurma = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        menuMedia = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        menuMinhaTurma1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbUserLogged = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbTitleMain = new javax.swing.JLabel();
        painelMain = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbTurma = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controlo Académico");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));

        menuHome.setBackground(new java.awt.Color(40, 40, 40));
        menuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHomeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuHomeMousePressed(evt);
            }
        });
        menuHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-casa-15.png"))); // NOI18N
        jLabel3.setText("  Home");
        menuHome.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel9.setBackground(new java.awt.Color(40, 40, 40));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnTerminarSessão.setBackground(new java.awt.Color(40, 40, 40));
        pnTerminarSessão.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnTerminarSessãoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnTerminarSessãoMousePressed(evt);
            }
        });
        pnTerminarSessão.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(153, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sair.png"))); // NOI18N
        jLabel18.setText("Terminar Sessão");
        pnTerminarSessão.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel8.setBackground(new java.awt.Color(13, 13, 13));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        menuMinhaTurma.setBackground(new java.awt.Color(40, 40, 40));
        menuMinhaTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMinhaTurmaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuMinhaTurmaMousePressed(evt);
            }
        });
        menuMinhaTurma.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-classe-15.png"))); // NOI18N
        jLabel13.setText("Minhas Turmas");
        menuMinhaTurma.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        menuMedia.setBackground(new java.awt.Color(40, 40, 40));
        menuMedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMediaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuMediaMousePressed(evt);
            }
        });
        menuMedia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-classe-15.png"))); // NOI18N
        jLabel14.setText("Médias");
        menuMedia.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        menuMinhaTurma1.setBackground(new java.awt.Color(40, 40, 40));
        menuMinhaTurma1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMinhaTurma1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuMinhaTurma1MousePressed(evt);
            }
        });
        menuMinhaTurma1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-classe-15.png"))); // NOI18N
        jLabel15.setText("Todas Turmas");
        menuMinhaTurma1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTerminarSessão, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(menuMinhaTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuMedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuMinhaTurma1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuHome, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuMinhaTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuMinhaTurma1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnTerminarSessão, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 440));

        jPanel2.setBackground(new java.awt.Color(0, 102, 94));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cardápio-30.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 37, 50));

        lbUserLogged.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        lbUserLogged.setForeground(new java.awt.Color(255, 255, 255));
        lbUserLogged.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-usuário-homem-com-círculo-30.png"))); // NOI18N
        lbUserLogged.setText("Hello, Admin");
        jPanel2.add(lbUserLogged, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, 30));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(40, 40, 40));
        jLabel4.setText("|");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sistema de Controlo Académico");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        jPanel7.setBackground(new java.awt.Color(230, 230, 230));

        lbTitleMain.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        lbTitleMain.setForeground(new java.awt.Color(0, 102, 94));
        lbTitleMain.setText("Página Inicial");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(lbTitleMain)
                .addGap(250, 250, 250))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitleMain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 690, 40));

        jtbTurma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Número", "Disciplina", "Ementa da disciplina"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbTurma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbTurmaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbTurma);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 2, 14)); // NOI18N
        jLabel2.setText("\"Todas as suas turmas \"");

        javax.swing.GroupLayout painelMainLayout = new javax.swing.GroupLayout(painelMain);
        painelMain.setLayout(painelMainLayout);
        painelMainLayout.setHorizontalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel2)
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
        );
        painelMainLayout.setVerticalGroup(
            painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(415, Short.MAX_VALUE))
            .addGroup(painelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(painelMainLayout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(painelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 680, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMouseClicked
        // TODO add your handling code here:
        MenuHome menuHome1 = new MenuHome();
        painelMain.removeAll();
        painelMain.add(menuHome1).setVisible(true);


    }//GEN-LAST:event_menuHomeMouseClicked

    private void menuHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHomeMousePressed
        // TODO add your handling code here:
        menuHome.setBackground(ClickedColor);
        menuMinhaTurma.setBackground(DefaultColor);
        menuMedia.setBackground(DefaultColor);
        lbTitleMain.setText("Página Inicial");
    }//GEN-LAST:event_menuHomeMousePressed

    private void pnTerminarSessãoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTerminarSessãoMouseClicked
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnTerminarSessãoMouseClicked

    private void pnTerminarSessãoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTerminarSessãoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnTerminarSessãoMousePressed

    private void menuMinhaTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMinhaTurmaMouseClicked
        // TODO add your handling code here:
        MenuMinhaTurma menuMinhaTurma = new MenuMinhaTurma();
        painelMain.removeAll();
        painelMain.add(menuMinhaTurma).setVisible(true);
    }//GEN-LAST:event_menuMinhaTurmaMouseClicked

    private void menuMinhaTurmaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMinhaTurmaMousePressed
        // TODO add your handling code here:
        menuHome.setBackground(DefaultColor);
        menuMinhaTurma.setBackground(ClickedColor);
        menuMedia.setBackground(DefaultColor);
        lbTitleMain.setText("Minha Turma");
    }//GEN-LAST:event_menuMinhaTurmaMousePressed

    private void jtbTurmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTurmaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jtbTurmaMouseClicked

    private void menuMediaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMediaMouseClicked
        // TODO add your handling code here:
        MenuMedia menuMinhaTurma = new MenuMedia();
        painelMain.removeAll();
        painelMain.add(menuMinhaTurma).setVisible(true);
    }//GEN-LAST:event_menuMediaMouseClicked

    private void menuMediaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMediaMousePressed
        // TODO add your handling code here:
        menuHome.setBackground(DefaultColor);
        menuMinhaTurma.setBackground(DefaultColor);
        menuMedia.setBackground(ClickedColor);
        lbTitleMain.setText("Médias por Turma");
    }//GEN-LAST:event_menuMediaMousePressed

    private void menuMinhaTurma1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMinhaTurma1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMinhaTurma1MouseClicked

    private void menuMinhaTurma1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMinhaTurma1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMinhaTurma1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorPainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorPainel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtbTurma;
    private javax.swing.JLabel lbTitleMain;
    private javax.swing.JLabel lbUserLogged;
    private javax.swing.JPanel menuHome;
    private javax.swing.JPanel menuMedia;
    private javax.swing.JPanel menuMinhaTurma;
    private javax.swing.JPanel menuMinhaTurma1;
    private javax.swing.JPanel painelMain;
    private javax.swing.JPanel pnTerminarSessão;
    // End of variables declaration//GEN-END:variables
}
